# Generated by Django 3.2.4 on 2021-06-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=64)),
                ('preview_img', models.TextField()),
                ('img', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('ref', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='scrapping.category')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='scrapping.press')),
            ],
        ),
    ]
