# Generated by Django 3.2.4 on 2021-06-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ref',
            field=models.URLField(),
        ),
    ]
