# Generated by Django 3.2.5 on 2021-07-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_code']},
        ),
    ]
